---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: echo-example
  labels:
    app: echo-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-example
  template:
    metadata:
      labels:
        app: echo-example
    spec:
      containers:
      - name: echo-example
        image: hashicorp/http-echo
        args:
        - "-text=echo"
        ports:
        - containerPort: 5678

---
kind: Service
apiVersion: v1
metadata:
  name: echo-example
spec:
  selector:
    app: echo-example
  ports:
  - port: 80
    targetPort: 5678
