kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - echo.fongshway.com
    secretName: letsencrypt-production
  rules:
  - host: echo.fongshway.com
    http:
      paths:
      - backend:
          serviceName: echo
          servicePort: 80
