---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: crystal-www-example
  labels:
    app: crystal-www-example
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crystal-www-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crystal-www-example
    spec:
      containers:
      - name: crystal-www-example
        image: fongshway/sample-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: crystal-www-example
spec:
  selector:
    app: crystal-www-example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
